[settings]
auto_install = true
lockfile = true

[tools]
# Root
hk = "1.36"
pkl = "0.30"

# Firmware
rust = {
  version = "1.93.1",
  targets = "riscv32imac-unknown-none-elf"
}

# Proto
buf = "1.65.0"

# Web
node = "24"
pnpm = "10.29.3"

[tasks]
pre-commit = ["hk fix"]

web-dev = { dir = "web", run = "pnpm dev" }
web-lint = {dir = "web", run = "pnpm lint" }
web-format = { dir = "web", run = "pnpm prettier" }
web-typecheck = { dir = "web", run = "pnpm typecheck" }

firmware-build-firmware = { dir = "firmware/firmware", run = "cargo build --target riscv32imac-unknown-none-elf" }
firmware-build-foundation-riscv = { dir = "firmware/foundation", run = "cargo build --target riscv32imac-unknown-none-elf" }
firmware-build-foundation-aarch64 = { dir = "firmware/foundation", run = "cargo build --target aarch64-apple-darwin" }
firmware-build-simulator = { dir = "firmware/simulator", run = "cargo -p build --target aarch64-apple-darwin" }
firmware-build = { depends = ["firmware-build-firmware", "firmware-build-foundation-riscv", "firmware-build-foundation-aarch64", "firmware-build-simulator"] }
