[settings]
auto_install = true
lockfile = true

[tools]
# Root
hk = "1.36"
pkl = "0.30"

# Firmware
rust = {
  version = "1.93.1",
  targets = "riscv32imac-unknown-none-elf,wasm32-unknown-unknown"
}

# Proto
buf = "1.65.0"

# Web
node = "24.13.1"
pnpm = "11.2.2"

[tasks]
pre-commit = ["hk fix"]

web-dev = { dir = "web", run = "pnpm dev" }
web-lint = {dir = "web", run = "pnpm lint" }
web-format = { dir = "web", run = "pnpm prettier" }
web-typecheck = { dir = "web", run = "pnpm typecheck" }

firmware-build-firmware = { dir = "firmware/firmware", run = "cargo build --target riscv32imac-unknown-none-elf" }
firmware-build-foundation-riscv = { dir = "firmware/foundation", run = "cargo build --target riscv32imac-unknown-none-elf" }
firmware-build-foundation-wasm32 = { dir = "firmware/foundation", run = "cargo build --target wasm32-unknown-unknown" }
firmware-build-simulator = { dir = "firmware/simulator", run = "cargo build" }
firmware-build-simulator-wasm-pack = { dir = "firmware/simulator", depends = ["firmware-build-simulator"], run = "wasm-pack build --target web --out-dir ../../web/simulator-pkg" }
firmware-build = { depends = ["firmware-build-firmware", "firmware-build-foundation-riscv", "firmware-build-foundation-wasm32", "firmware-build-simulator", "firmware-build-simulator-wasm-pack"] }
firmware-run-simulator = { dir = "firmware/simulator", run = "trunk serve --open --watch ../" }
