[package]
name = "foundation"
version = "0.1.0"
edition = "2024"
rust-version = "1.93.1"

[lib]
name = "foundation"
path = "src/lib.rs"

[dependencies]
embedded-graphics = { workspace = true }
prost = { version = "0.14.3", default-features = false, features = ["derive"] }
heapless = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
embassy-sync = { workspace = true, features = ["log"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
async-channel = { workspace = true }
