[workspace]
resolver = "3"
package = { edition = "2024" }
members = [
    "firmware",
    "foundation",
    "simulator"
]
# Ignore firmware when compiling the whole workspace
default-members = ["foundation", "simulator"]

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false

[workspace.dependencies]
log = { version = "0.4.27" }
embedded-graphics = { version = "0.8.2" }
heapless = { version = "0.9.2" }
static_cell = { version = "2.1.1" }
serde = { version = "1.0.228", default-features = false }
embassy-sync = { version = "0.7.2" }
async-channel = { version = "2.5.0" }
