name: CI (Firmware)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "firmware/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "firmware"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          targets: riscv32imac-unknown-none-elf,wasm32-unknown-unknown
          toolchain: "1.94.0"
          components: rust-src, rustfmt, clippy

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Build foundation (riscv)
        run: cargo build --target riscv32imac-unknown-none-elf --release
        working-directory: "firmware/foundation"

      - name: Build foundation (wasm)
        run: cargo build --target wasm32-unknown-unknown --release
        working-directory: "firmware/foundation"

      - name: Build firmware
        run: cargo build --target riscv32imac-unknown-none-elf --release
        working-directory: "firmware/firmware"

      - name: Build simulator
        run: cargo build --target wasm32-unknown-unknown --release
        working-directory: "firmware/simulator"

      - name: Check formatting
        run: cargo fmt --all -- --check
        working-directory: "firmware"

      # Clippy not working right now due to some issues with the riscv target, will re-enable once those are resolved
      # - name: Run clippy
      #   run: cargo clippy --all-features --workspace -- -D warnings
      #   working-directory: "firmware"
